### ISSUE TITLE
Improve Caliper documentation

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#507]
## Context
This is a general issue relating to the current state of the documentation. Before Caliper is published to npm (thus increasing its usability and making it more widespread hopefully), the documentation must also be improved in several areas (prompted by #506). 

## Tasks
I've gathered the following tasks so far relating to improving the documentation. These can be refined after further discussions.

1. [ ] Consolidate the structure/outline (categories, [new] pages, order, etc)
1. [ ] Move and rewrite current content as needed (some pages are really packed right now)
1. [ ] Fill the empty placeholder pages with new content (mainly tutorials, Q&A, etc)
1. [ ] Eliminate typos

**Comment by jeffywu** [comment]
Hi, happy to help with the documentation. Is there any appetite for merging the gh_pages branch into master and putting it into a /doc folder on the master branch? This would save having to create two PRs when adding a feature and improving the documentation. Also the benefit of being able to pull the docs down locally with one fetch.
https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

> You can configure GitHub Pages to publish your site's source files from master, gh-pages, or a /docs folder on your master branch for Project Pages and other Pages sites that meet certain criteria.

**Comment by aklenik** [comment]
@jeffywu Every help is welcome! It's always useful to get yet another perspective on the documentation. The core developers might be a bit biased about what's trivial and what needs additional explanation, so we're glad for every feedback.

The docs dir was the original approach, but it was hard to navigate, and a little hard to maintain. Having a separate branch makes it easier to separate the code from the docs (both for reviews, and updates).

(A personal experience: it always bothered me that I can't clearly follow only the docs changes in fabric, for example. With a separate doc-only branch, it's easier to re-read the changed part of the docs)

**Comment by jeffywu** [comment]
Is there a part of the docs that you think need the most work right now?

**Comment by aklenik** [comment]
In the architecture page, there are a few things that could be separated. For example, I'd give its own page to the following topics:
* General architecture 
* Test configuration file structure and description 
* User defined test modules 
* (Zookeeper will be removed soon) 

And the everlasting battle against typos of course :D

**Comment by davidkel** [comment]
Closing as we now have a new format for documentation which hopefully has addresses the outstanding issues around structure here. The assumption is that the other concerns have already been addressed.
