### ISSUE TITLE
Consolidate connector API

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#888]
## Context
As a prerequisite for adding TX builder support (#858), the connectors' TX API should be simplified/streamlined.

## Actual Behavior
1. Passing the context around between the workload module and the connector is meaningless. The workload gets the context during its initialization, the connectors also save the same instance. No need to pass it around.
2. The invoke/query APIs support batch requests, but the target contract, version, and timeout must be the same, only the arguments can differ. This is not realistic/flexible.
3. The invoke and query API is separated, but the difference is mainly on the SUT side, the client-side semantics/parameters are similar. Currently, it's difficult to mix invokes and queries in the same batch, since it requires the merging of result arrays in the workload modules.

## Expected Behavior
1. Remove the context from the API.
2. With the context removed, merge the contract, version, and timeout settings into the arguments object. This will result in a single `invokeSettings` parameter for the functions, which can also be an array.
3. The invoke and query function can be merged if we add a `query: true/false` attribute to the settings object above. This results in a single API function, expecting a single settings parameter, which can also be an array, now containing the mix of queries and invokes.

## Tasks
- [x] Remove context from API (#899)
- [x] Make TX reporting even oriented (#927)
- [x] Remove legacy `queryState` functions (#931)
- [x] Merge invoke/query parameters into a single object (#949)
- [ ] Merge invoke/query functions into a single function

## Your Environment

* Version used: v0.3.2

**Comment by nklincoln** [comment]
At the moment the `init()` function is being used to initialise both the connector and the SUT for some adaptors. It would be good to remove this overloading by either having the connector init only on creation, or provide explicit `initConnector` and `initSUT` methods. My preference would be the latter due to some adaptors requiring an asynchronous init as they query for information on the SUT (Fabric)

**Comment by aklenik** [comment]
I also support the `initConnector` and `initSUT` approach. I guess this means that worker processes won't even call the `initSUT` function. 

Separating the local and remote inits might not be that easy. For example, loading user connection profiles for Fabric sometimes requires enrolling new users, which requires SUT access. So separating these will need extra considerations and code. To this end, I'd open a separate issue for the init splitting. 

(The removal of `queryState` fits nicely into the invoke API refactor.)

**Comment by aklenik** [comment]
Additional refactors in the connector API:
1. `get/releaseContext` is basically a `before/afterRound` call. If the context stays inside the connector, we should also hide the name.
2. Putting the TX count callback into the returned context is... ugly. Connectors should provide events, like `onTxSubmitted`, and anyone can register a callback for that. The same goes for other modules, like the messenger or orchestrators if needed.

**Comment by aklenik** [comment]
@nklincoln Adding to my previous comment's 2nd point: if we also expose a `txsFinished` event on the connectors, then the CaliperWorker class can directly subscribe to the `txsSubmitted/txsFinished` events, so the worker modules don't need to return them anymore, and hopefully, the `setImmediate` loop part will become cleaner.
