### ISSUE TITLE
As a Caliper user, I would like Fabric network configuration files to be more understandable, so that I can create them with greater ease

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#940]
Caliper network configuration files can be very confusing, which is a result of how they have evolved over time. We need to consider that the file is used by Caliper, and should consequently should be shaped in a way that suits the use within Caliper rather than being beholding to the target connector.

Configuration files for the Fabric connector should:

- [x] Point to a connection profile, instead of extending one
- [x] Specify identities to use when testing, which may be one, or a combination of:
  - [x] One or more (file) wallets, from which identities are used, without having to nest a larger client description
  - [x] An identity backed with existing certificates
  - [x] An identity name to be registered/enrolled, using available registrar information (DROPPED)
- [x] Indicate if the network being targeted has discovery enabled or not
- [x] Not require unnecessary administrative certificates if not explicitly required

It would be nice if the above considerations could be introduced, such that it is more obvious how the network configuration file is constructed, and subsequently consumed by caliper.

**Comment by davidkel** [comment]
![image](https://user-images.githubusercontent.com/25582377/91459722-dc6ee580-e87e-11ea-9a5c-8b70ee0d45de.png)

**Comment by davidkel** [comment]
Proposed new format for fabric adapter configuration (caveat, may still have minor iterative changes as this issue is progressed)
```
---
# The name of the benchmark
name: Geoff
# The caliper semantic version
version: "1.0.0"

# Global properties that define the SUT, and options that are specific to the target SUT
caliper:
    blockchain: fabric,
    sutOptions :
       mutualTls: true

# Array of fabric channels for creation or use
channels:
    - channelName: my-channel
      # [Optional] create the channel
      create: true
      definition:
        capabilities: []
        consortium: 'SampleConsortium2'
        msps: ['Org1MSP', 'Org2MSP']
        version: 0
        orderers:
        - orderer0.example.com
        - orderer1.example.com
        peers:
            peer0.org1.example.com:
                eventSource: true
            peer0.org2.example.com:
                eventSource: true
      # Array of contracts to be installed/instantiated on the named channel and available for use by the workload module
      contracts:
      - id: marbles
        contractID: myMarbles
        version: v0
        language: golang
        path: marbles/go
        metadataPath: src/marbles/go/metadata

    - channelName: your-channel
      create: false
      contracts:
      - id: marbles
        contractID: lostMyMarbles
        version: v0

# [Minimum 1] Array of organizations that are to be used within the benchmarking, containing one of more identities to be used by the connector
organizations:
  - mspid: org1MSP
    # One or more identity specification types that may provide a unique identity for the use by the connector.
    identities:
      # [Optional] only used for fabric connector not gateway (can also be defined in connection profile)
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
            path: /tmp/hfc-cvs/org1
      #  [Optional] File path to a FileWallet, within which all entries are all for the same org. Only for use by gateway
      wallet:
         path: 'some/path/to/org-specific-wallet'
      # [Optional] certificates for the client
      certificates:
      - name: 'User1'
        clientPrivateKey:
            # can use PEM as well, ie pem: < text >
            path: ../config/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/key.pem
        clientSignedCert:
            path: ../config/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem..
    # Connection profile to be used by the connector for the organization
    # - could validate this connection profile matches declared mspid
    connectionProfile: {
         path: 'some/path/to/org-specific-profile',
         discover: true
     }
  - mspid: org2MSP
    # and so forth
```

**Comment by davidkel** [comment]
Final format is documented here now
```
---
# The name of the benchmark
name: BasicConfig
# The caliper semantic version, 2.0.0 defines this new version
version: "2.0.0"

# Global properties that define the SUT, and options that are specific to the target SUT
caliper:
  blockchain: fabric
  sutOptions :
    mutualTls: true

# Array of fabric channels for creation or use
channels:
  - channelName: mychannel
    # [Optional] create the channel
    create:
      buildTransaction:
        capabilities: []
        consortium: 'SampleConsortium2'
        msps: ['Org1MSP', 'Org2MSP']
        version: 0
      # Array of contracts to be installed/instantiated on the named channel and available for use by the workload module
    contracts:
    - id: marbles
      contractID: myMarbles
      # define the install requirements to install chaincode if chaincode is to be installed
      install:
        version: v0
        language: golang
        path: marbles/go
        metadataPath: src/marbles/go/metadata
      # define the instantiate requirements to instantiate chaincode. All of this section is optional depending on chaincode requirements
      instantiate:
        initFunction: init
        initArguments: []
        initTransientMap:
          key1: value1
          key2: value2
        endorsementPolicy: ''
        collectionsConfig: ''

  - channelName: somechannel
    create:
      # use a pre-built channel transaction. Alternative to buildTransaction option shown above
      prebuiltTransaction: 'channel.tx'
    contracts:
    - id: marbles
      contractID: foundMyMarbles

  - channelName: yourchannel
    contracts:
    - id: marbles
      contractID: lostMyMarbles

# [Minimum 1] Array of organizations that are to be used within the benchmarking, containing one of more identities to be used by the connector
organizations:
  - mspid: Org1MSP
    # One or more identity specification types that may provide a unique identity for the use by the connector. There must be at least 1
    identities:
      # [NOT CURRENTLY SUPPORTED] [Optional] only for use by non gateway fabric connector (could also be defined in connection profile) of a node sdk credential and crypto store
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
            path: /tmp/hfc-cvs/org1
      #  [Optional] File path to a FileWallet, within which all entries are all for the same org. Only for use by gateway
      wallet:
        path: './test/sample-configs'
        adminNames:
        - admin
      # [Optional] certificates for the client
      certificates:
      - name: 'User1'
        clientPrivateKey:
          # choice of path or pem
          pem: |-
            -----BEGIN PRIVATE KEY-----
            -----END PRIVATE KEY-----
        clientSignedCert:
          # choice of path or pem
          pem: |-
            -----BEGIN CERTIFICATE-----
            -----END CERTIFICATE-----
    # Connection profile to be used by the connector for the organization
    connectionProfile:
      # the path to this connection profile
      path: './test/sample-configs/Org1ConnectionProfile.yaml'
      # [Optional] whether this connection profile requires to be discovered (ie it is a dynamic connection profile) default is false if not specified.
      discover: true
  - mspid: Org2MSP
    identities:
      certificates:
      - name: 'User1'
        clientPrivateKey:
          path: '/path/to/some/privatekey.pem'
        clientSignedCert:
          path: '/path/to/some/publiccert.pem'
    connectionProfile:
      path: './test/sample-configs/StaticOrg2ConnectionProfile.json'
      discover: false
```

**Comment by davidkel** [comment]
To finalize the above diagram there won't be 
- any further integration tests
- a validator for the new above connector configuration
- a validator for the fabric connection profiles (as there is now no real formal specification of it)
- and there are no samples to update

Operational support is in PR now, outstanding for this is
- documentation
- tutorial
- auto identity selection
- more runtime validation of a network configuration file
- some minor bug fixes
